name: CI/Cd for Github Action Demo

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEMO_TITLE: ${{vars.DEMO_TITLE}}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          name: github-pages-${{ github.run_id }}
          path: .

      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages-${{ github.run_id }}
