name: Deploy on FTP

on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Verify secrets are set
        run: |
          echo "Verifying secrets are available..."
          if [ -z "${{ secrets.FTP_SERVER }}" ]; then
           echo "ERROR: FTP_SERVER secret is not set"
           exit 1
          fi
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
           echo "ERROR: FTP_USERNAME secret is not set"
           exit 1
          fi
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
           echo "ERROR: FTP_PASSWORD secret is not set"
           exit 1
          fi
          if [ -z "${{ secrets.FTP_PORT }}" ]; then
           echo "ERROR: FTP_PORT secret is not set"
           exit 1
          fi
          echo "All secrets are properly set!"

      - name: Show remote root (diagnose)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          FTP_PORT: ${{ secrets.FTP_PORT }}
        run: |
          echo "Listing remote root via FTP (secrets masked in logs)..."
          sudo apt-get update -qq
          sudo apt-get install -y lftp -qq
          # list remote root (will be masked in logs)
          lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -p "$FTP_PORT" "$FTP_SERVER" -e "cls -la; bye"

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./
          server-dir: / # try /public_html/ if root doesn't serve your site
